add logger util

diff --git a/cronlogd/loggerctl b/cronlogd/loggerctl
--- a/cronlogd/loggerctl
+++ b/cronlogd/loggerctl
@@ -2,9 +2,17 @@
 
 LOGGER_ETC_HOME=${LOGGER_ETC_HOME:-$HOMEBREW_PREFIX/etc/loggerd.d}
 LOGGER_RUNNING_HOME=${LOGGER_RUNNING_HOME:-$HOMEBREW_PREFIX/var/run/loggerd}
-LOGGER_PIPE_HOME=${LOGGER_PIPE_HOME:-$LOGGER_RUNNING_HOME/pipe}
-LOGGER_FILE_STORE=${LOGGER_FILE_STORE:-$LOGGER_RUNNING_HOME/store}
+LOGGER_PIPE_HOME=$LOGGER_RUNNING_HOME/pipe
+LOGGER_FILE_STORE=$LOGGER_RUNNING_HOME/store
+LOGGER_DAEMON_PID_FILE=$LOGGER_RUNNING_HOME/.daemon.pid
 LOGGER_CONFIG_FILE=$LOGGER_ETC_HOME/logger.conf
+
+function check_daemon
+{
+	[ -r "$LOGGER_DAEMON_PID_FILE" ] && daemon_pid=$(cat "$LOGGER_DAEMON_PID_FILE")
+	[ "$daemon_pid" ] && kill -0 "$daemon_pid" 2>/dev/null && return 0
+	return 1
+}
 
 function usage()
 {
@@ -57,7 +65,6 @@ function save_logger
 function delete_logger
 {
 	local logger=$1
-
 
 	[ -f "$LOGGER_RUNNING_HOME/$logger.run" ] && {
 		echo "try stop logger first"
@@ -114,6 +121,8 @@ function start_logger
 	outpath=${outpath%:*}
 	local period=${logger_config##*:}
 
+	[ -d "$outpath" ] || mkdir -p "$outpath"
+
 	run_logger_daemon "$logger" "$outpath" "$period"
 	echo "Start Logger $logger success!"
 }
@@ -131,10 +140,38 @@ function stop_logger
 	echo "Stop Logger $logger success!"
 }
 
-function list_logger
+function status
 {
-	gawk -F: 'NR == FNR { out[$1]=$2; period[$1]=$3; } NR > FNR { pipe[$1]=$3; pid[$1]=$2; } END {printf "%-30s %-8s %-60s %-60s %-8s %-s\n", "LOGGER", "ROLLING", "INPUT_PIPE", "OUTPUT_PATH", "PID", "STATUS";   for (logger in out) { status="";  if(logger in pid) {"kill -0 "pid[logger]" 2>/dev/null && echo running || echo dead" | getline status}; printf "%-30s %-8s %-60s %-60s %-8s %-s\n", logger, period[logger], pipe[logger], out[logger], pid[logger], status; }}' "$LOGGER_CONFIG_FILE" "$LOGGER_RUNNING_HOME"/.running
+	cd "$LOGGER_RUNNING_HOME"
+	ls *.run | sed -e 's/\.run$//' | gawk -F: 'NR == FNR { 
+			out[$1]=$2; 
+			period[$1]=$3; 
+			run[$1]="stop";
+		} 
+		FILENAME ~ /\.running$/ { 
+			pipe[$1]=$3; 
+			pid[$1]=$2; 
+		} 
+		FILENAME == "-" {
+			run[$1]="starting";
+		}
+		END {
+			format="%-30s %-8s %-60s %-60s %-8s %-s\n"; 
+			printf format, "LOGGER", "ROLLING", "INPUT_PIPE", "OUTPUT_PATH", "PID", "STATUS";   
+			for (logger in out) { 
+				status=run[logger];  
+				if(logger in pid) {
+					"kill -0 "pid[logger]" 2>/dev/null && echo running || echo dead" | getline status
+				}; 
+				printf format, logger, period[logger], pipe[logger], out[logger], pid[logger], status; 
+			}
+		}' "$LOGGER_CONFIG_FILE" "$LOGGER_RUNNING_HOME"/.running -
 }
+
+if ! check_daemon; then
+	echo "Fatal Error: Logger daemon is not running!"
+	exit 10
+fi
 
 cmd=$1
 shift
@@ -188,8 +225,8 @@ stop)
 delete)
 	delete_logger "$try_logger"
 	;;
-list|status) 
-	list_logger
+list | status)
+	status
 	;;
 *)
 	usage
